### ISSUE TITLE
Error After installing Angular Material 

### ISSUE THREAD

**Issue by tango4567** [nkoehler/mat-video#27]
After installing Angular Material project is showing the following error

```
Failed to compile.
./node_modules/@angular/material/esm5/button.es5.js
Module build failed: Error: ENOENT: no such file or directory, open '/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@angular/material/esm5/button.es5.js'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Storage.provideSync (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable._subscribe (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@ngtools/webpack/src/compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:39:54)
    at processResource (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/webpack/lib/NormalModule.js:280:3)
    at NormalModule.build (/media/tango/WorkSpace/IonicProject/mat-video-test/node_modules/webpack/lib/NormalModule.js:427:15)
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: ^8.0.1
Material: ^5.2.0
OS: Ubuntu 19.04
TypeScript: ~3.1.6

**Comment by nkoehler** [comment]
Your angular material version should be 8.0.1 if you plan on using Angular 8.
